apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourceallocations.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                quantumDuration:
                  type: string
                users:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      slo:
                        type: string
                      qps:
                        type: integer
                      demand:
                        type: integer
                alpha:
                  type: number
                f:
                  type: integer
            status:
              type: object
              properties:
                allocations:
                  type: object
                  additionalProperties:
                    type: integer
                credits:
                  type: object
                  additionalProperties:
                    type: integer
  scope: Namespaced
  names:
    plural: resourceallocations
    singular: resourceallocation
    kind: ResourceAllocation
    shortNames:
      - ralloc